---

- name: Setup OpenRA server
  hosts: openra_server
  remote_user: root
  roles:
  - role: openra_server
      openra_server_names:
        - "Lyra OpenRA Server 1"
        - "Lyra OpenRA Server 2"
