---

- name: Ensure project config directory exists
  file:
    path: '/opt/docker/configs/{{ docker_container_name }}'
    state: directory

- name: Stop docker services
  docker_compose:
    project_src: '/opt/docker/configs/{{ docker_container_name }}'
    state: absent

- name: Add docker-compose.yml file
  template:
    src: 'docker-compose.yml.j2'
    dest: '/opt/docker/configs/{{ docker_container_name }}/docker-compose.yml'

- name: Ensure docker services started
  docker_compose:
    project_src: '/opt/docker/configs/{{ docker_container_name }}'
    pull: yes
